name: Workflow
on:
  push:
    branches:
      - 'main'
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  php-stan:
    name: PHP Stan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts

      - name: Run PHPStan
        run: ./vendor/bin/phpstan

  php-unit:
    name: PHP Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
